name: Visual Regression Tests (Sharded)

on:
  push:
    branches: [ visual_testing/Alibek ]
  pull_request:
    branches: [ visual_testing/Alibek ]
  workflow_dispatch:

jobs:
  # JOB 1: Run the tests (split across 2 agents)
  visual-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-jammy

    strategy:
      fail-fast: false #In case shard 1 fails, shard 2 continues working
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]  
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      
      - name: Run Playwright Tests (Sharded)
        # --shard=x/y: Splits the tests
        # --workers=1: Ensures stability for visual snapshots
        # --reporter=blob: Create raw data instead of HTML
        run: |
          npx playwright test tests/visual/ \
          --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} \
          --workers=1 \
          --retries=2 \
          --reporter=blob

      - name: Upload Blob Report
        # Uploads the raw data from THIS specific agent
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

  # JOB 2: Merge the reports
  merge-reports:
    if: always() # Run even if tests failed
    needs: [visual-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Download All blob reports
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          path: all-blob-reports
          merge-multiple: true

      - name: Merge reports into HTML
        run: npx playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload Final HTML report
        uses: actions/upload-artifact@v4
        with: 
          name: visual-diff-report
          path: playwright-report
          retention-days: 30

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
